#define MAINPREFIX z
#define PREFIX avo
#define MOD_NAME Advanced Vanilla Objects
#define AUTHOR "Andx"

#define REQUIRED_VERSION 2.22

#include "script_version.hpp"

#define VERSION MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH
#define VERSION_AR MAJOR,MINOR,PATCH

#ifndef COMPONENT_BEAUTIFIED
    #define COMPONENT_BEAUTIFIED COMPONENT
#endif
#define COMPONENT_NAME QUOTE(MOD_NAME - COMPONENT_BEAUTIFIED)
