[default]
workshop = [
    "450814997",  # CBA_A3
    "463939057",  # ACE3
]
# Test mission with the vanilla objects the addons add functions to, in .hemtt/missions/
mission = "test.VR"

# Launched with `hemtt launch acre` / `hemtt launch bwa3`
[acre]
extends = "default"
workshop = [
    "751965892",  # ACRE2
]

[bwa3]
extends = "default"
workshop = [
    "1200127537", # BWMod
]
